- hosts: all
  tasks:
    - name: Install node exported
      shell:
        cmd: |
          wget https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz
          tar xzf node_exporter-1.1.2.linux-amd64.tar.gz
          sudo mv -v node_exporter-1.1.2.linux-amd64/node_e
          xporter /usr/local/bin/
          sudo chown root:root /usr/local/bin/node_exporter